spring:
  profiles:
    active: peer1
  log:
    level: INFO

logging:
  file: ./logs/log.log

---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/
    register-with-eureka: true
    fetch-registry: true
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
    register-with-eureka: true
    fetch-registry: true
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer3
server:
  port: 8763
eureka:
  instance:
    hostname: peer3
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
    register-with-eureka: true
    fetch-registry: true